# Generated by Django 3.2.11 on 2022-01-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_blog', '0006_auto_20220120_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sort_order',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='new category', max_length=200, verbose_name='Título categoría'),
        ),
    ]
