# Generated by Django 3.2.11 on 2022-01-20 18:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('tech_blog', '0008_auto_20220120_1443'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleDetail',
            new_name='ArticleDetailPage',
        ),
    ]
