# Generated by Django 3.2.11 on 2022-01-20 21:16

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('tech_blog', '0009_rename_articledetail_articledetailpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articledetailpage',
            name='article_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen del Artículo'),
        ),
        migrations.AlterField(
            model_name='articledetailpage',
            name='content',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Contenido'),
        ),
        migrations.DeleteModel(
            name='ArticleListingPage',
        ),
    ]
