# Generated by Django 3.2.11 on 2022-01-23 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_blog', '0010_auto_20220120_1716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articledetailpage',
            options={'verbose_name': 'Artículo', 'verbose_name_plural': 'Artículos'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=2, help_text='Es un nombre mas facil de recordar para las categorías', max_length=255, verbose_name='nombre amigable'),
            preserve_default=False,
        ),
    ]
