# Generated by Django 3.2.11 on 2022-01-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_blog', '0011_auto_20220123_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='nueva categoría', help_text='Es un nombre mas facil de recordar para las categorías', max_length=255, verbose_name='nombre amigable'),
        ),
    ]
